vive:
    world_name: "libsurvive_world"
    tracker_left: "LHR-F30CC195_imu"
    tracker_right: ""
    teleop_base: "tracker_base"
    left_hand: "left_hand"
    right_hand: "right_hand"
    base_station_1: ""
    base_station_2: ""

    esp32_topic_name: "/esp32_json_string"
    joystick_topic: "/joystick"
    cmd_left_name: "/pos_cmd"
    cmd_right_name: ""

    #joystick param
    middle_value: 2420
    deadband: 100
    button_press_time: 25
    button_single_press: 4

    #机械臂初始化tcp坐标系
    base_x: 0.05
    base_y: 0
    base_z: 0.2
    base_roll: 0
    base_pitch: 0
    base_yaw: 0

    #hand相对追踪器的坐标
    hand_x: 0
    hand_y: 0
    hand_z: -0.05
    hand_roll: 0
    hand_pitch: 0
    hand_yaw: 3.14

    joint_num: 7

    init_angle:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0